# numpy

In [1]:
import numpy as np
lst = [[1,3,5],[2,4,6]]
print(type(lst))

<class 'list'>


创建numpy中的array

In [3]:
np_list = np.array(lst)
print(type(np_list))

<class 'numpy.ndarray'>


创建特定类型的array
+ int
+ float
+ int8
+ int16
+ int32
+ int64
+ int128
+ uint8
...
+ float
+ float16
...
+ str

In [5]:
np_lst = np.array(lst, dtype=np.float)
print(np_lst)

[[ 1.  3.  5.]
 [ 2.  4.  6.]]


In [10]:
print(np.size(np_lst))

6


一些常用的数组

In [17]:
# 零数组
print("zeros([2, 4]):")
print(np.zeros([2,4]))
# 一数组
print("ones([3, 5]):")
print(np.ones([3, 5]))
# 随机数数组
print('np.random.rand(2, 4):')
print(np.random.rand(2, 4))
# 一个随机数
print('np.random.rand():')
print(np.random.rand())
print('np.random.randint(1, 10):')
print(np.random.randint(1, 10, [2, 5]))
#标准正态分布的随机数
print('np.random.randn(2, 4):')
print(np.random.randn(2, 4))
# 从给定数组中获取随机数(必须是一维数组)
print('np.random.choice([3,5,7,9,6,4,1]):')
print(np.random.choice([3,5,7,9,6,4,1]))


zeros([2, 4]):
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
ones([3, 5]):
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
np.random.rand(2, 4):
[[ 0.76690586  0.2286677   0.5681215   0.24779852]
 [ 0.37705609  0.42749176  0.17434173  0.32968999]]
np.random.rand():
0.5385542803445688
np.random.randint(1, 10):
[[2 3 5 9 3]
 [2 4 2 5 7]]
np.random.randn(2, 4):
[[-1.12495895  1.42832763  1.59524508  0.50788032]
 [-0.21779095 -0.09808772 -1.21915244  0.29229889]]
np.random.choice([3,5,7,9,6,4,1]):
7


numpy的一些操作

In [20]:
print('np.arange(1, 11):')
print(np.arange(1, 11))
# 转换为两行五列的列表
print('np.arange(1, 11).reshape(2, 5):')
print(np.arange(1, 11).reshape(2, 5))

# 数组点乘
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print('np.dot(arr1, arr2.reshape(4,1))')
print(np.dot(arr1, arr2.reshape(4, 1)))

# 追加
print('np.concatenate((arr1, arr2))')
print(np.concatenate((arr1, arr2)))
print('np.hstack((arr1, arr2))')
print(np.vstack((arr1, arr2)))
print('np.hstack((arr1, arr2))')
print(np.hstack((arr1, arr2)))

np.arange(1, 11):
[ 1  2  3  4  5  6  7  8  9 10]
np.arange(1, 11).reshape(2, 5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
np.dot(arr1, arr2.reshape(4,1))
[70]
np.concatenate((arr1, arr2))
[1 2 3 4 5 6 7 8]
np.hstack((arr1, arr2))
[[1 2 3 4]
 [5 6 7 8]]
np.hstack((arr1, arr2))
[1 2 3 4 5 6 7 8]
