In [13]:
import numpy as np

a = np.random.rand(5)
print(a)

[ 0.35545053  0.2490816   0.97547411  0.86331543  0.31292715]


In [18]:
import math

# 非向量化的做法
u = np.zeros(5)
for i in range(5):
    u[i] = math.exp(a[i])
print(u)

u = np.zeros(5)
# 向量化的做法
u = np.exp(a)
print(u)

[ 1.42682334  1.28284671  2.65242445  2.37100859  1.36742191]
[ 1.42682334  1.28284671  2.65242445  2.37100859  1.36742191]


In [21]:
# 更多的例子
print(np.log(a))

print(np.abs(a))

print(a**2)

print(1/a)

print(np.maximum(a,0))

[-1.03436919 -1.38997471 -0.02483166 -0.14697515 -1.16178486]
[ 0.35545053  0.2490816   0.97547411  0.86331543  0.31292715]
[ 0.12634508  0.06204165  0.95154974  0.74531353  0.0979234 ]
[ 2.81333099  4.01474852  1.02514253  1.15832518  3.19563194]
[ 0.35545053  0.2490816   0.97547411  0.86331543  0.31292715]
